import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-dim': '#759aff',
        'on-error': '#490006',
        'primary-container': '#00d2fd',
        'surface-tint': '#6dddff',
        'surface-container-low': '#131313',
        'on-surface-variant': '#adaaaa',
        'outline': '#767575',
        'secondary-container': '#006687',
        'surface-container-high': '#20201f',
        'on-background': '#ffffff',
        'outline-variant': '#484847',
        'primary-fixed-dim': '#00c3eb',
        'inverse-surface': '#fcf9f8',
        'on-primary-fixed-variant': '#004c5d',
        'secondary-dim': '#00b3e9',
        'on-secondary-fixed-variant': '#005774',
        'on-secondary': '#00374b',
        'on-secondary-container': '#f1f9ff',
        'surface-container-lowest': '#000000',
        'on-secondary-fixed': '#00394d',
        'inverse-primary': '#00687e',
        'tertiary-fixed-dim': '#7da0ff',
        'surface-container-highest': '#262626',
        'primary-fixed': '#00d2fd',
        'on-primary-fixed': '#002c37',
        'secondary': '#03c1fb',
        'surface-variant': '#262626',
        'on-primary': '#004c5e',
        'error': '#ff716c',
        'surface-dim': '#0e0e0e',
        'tertiary-fixed': '#92aeff',
        'surface-container': '#1a1a1a',
        'background': '#0e0e0e',
        'primary': '#6dddff',
        'tertiary-container': '#6f94fa',
        'surface-bright': '#2c2c2c',
        'error-dim': '#d7383b',
        'secondary-fixed': '#94dbff',
        'tertiary': '#82a3ff',
        'error-container': '#9f0519',
        'on-primary-container': '#004352',
        'surface': '#0e0e0e',
        'inverse-on-surface': '#565555',
        'on-tertiary': '#002363',
        'on-tertiary-container': '#001747',
        'on-error-container': '#ffa8a3',
        'on-tertiary-fixed': '#001442',
        'on-tertiary-fixed-variant': '#003388',
        'secondary-fixed-dim': '#67cfff',
        'primary-dim': '#00c3eb',
        'on-surface': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'neon-glow': '0 0 15px rgba(109, 221, 255, 0.1)',
        'neon-glow-hover': '0 0 25px rgba(109, 221, 255, 0.25)',
      },
    },
  },
  plugins: [],
};

export default config;
